<?php
/**
 * Zikula Application Framework
 *
 * @copyright (c) 2008, Zikula Development Team
 * @link http://www.zikula.org
 * @license GNU/GPL - http://www.gnu.org/copyleft/gpl.html
 * @package Zikula_Generated_Modules
 * @subpackage locations
 * @author Steffen Voﬂ
 * @url http://kaffeeringe.de
 */

/*
 * generated at Fri Jul 04 17:14:11 GMT 2008 by ModuleStudio 0.4.10 (http://modulestudio.de)
 */


include_once('modules/locations/pnlang/eng/common.php');

// interactive init procedure
define('_LOCATIONS_INIT',                                         'Installation of locations');
define('_LOCATIONS_INIT_WELCOME',                                 'Welcome to the installation of locations');
define('_LOCATIONS_INIT_COPY',                                    'Generated by ModuleStudio, http://modulestudio.de');
define('_LOCATIONS_INIT_FEATURES',                                'For example locations contains the following functions:');
define('_LOCATIONS_INIT_FEATURE1TITLE',                           'Feature 1');
define('_LOCATIONS_INIT_FEATURE1HINT',                            'Easy management of ---');
define('_LOCATIONS_INIT_FEATURE2TITLE',                           'Feature 2');
define('_LOCATIONS_INIT_FEATURE2HINT',                            'Create ---');
define('_LOCATIONS_INIT_FEATURE3TITLE',                           'Feature 3');
define('_LOCATIONS_INIT_FEATURE3HINT',                            '---');
define('_LOCATIONS_INIT_FEATURE4TITLE',                           'Feature 4');
define('_LOCATIONS_INIT_FEATURE4HINT',                            '---');
define('_LOCATIONS_INIT_FEATURETECHTITLE',                        'locations uses the current technologies of PostNuke .8');
define('_LOCATIONS_INIT_FEATURETECHHINT',                         'All parts of locations are always up to state-of-the-art.');
define('_LOCATIONS_INIT_SETTINGS',                                'Settings');
define('_LOCATIONS_INIT_ACTION',                                  'Action');

define('_LOCATIONS_INIT_STEP3',                                   'Last installation step');
define('_LOCATIONS_INIT_THANKS',                                  'Thank you for installing locations.<br />Click on the bottom link to finish the installation.');
define('_LOCATIONS_ACTIVATE',                                     'Activate locations after installation?'); 
define('_LOCATIONS_DELETE',                                       'Uninstall of locations');
define('_LOCATIONS_DELETE_THANKS',                                'Thank you for using locations.<br />The module is going to be removed now!');


define('_LOCATIONS_INIT_DEFAULTDATAPROBLEM',                      'Failed to create default data');
define('_LOCATIONS_INIT_CATEGORYPROBLEM',                         'Failed to create categories');

// default data



// default data for location table

define('_LOCATIONS_LOCATION_1_LOCATIONID', '1');
define('_LOCATIONS_LOCATION_1_NAME', 'Schaubude');
define('_LOCATIONS_LOCATION_1_STREET', 'Legienstraﬂe 40');
define('_LOCATIONS_LOCATION_1_ZIP', '24103');
define('_LOCATIONS_LOCATION_1_CITY', 'Kiel');
define('_LOCATIONS_LOCATION_1_PHONE', '');
define('_LOCATIONS_LOCATION_1_FAX', '');
define('_LOCATIONS_LOCATION_1_URL', 'http://www.kieler-schaubude.de');
define('_LOCATIONS_LOCATION_1_EMAIL', '');
define('_LOCATIONS_LOCATION_1_COUNTRY', 'Germany');
define('_LOCATIONS_LOCATION_1_STATE', 'Schleswig-Holstein');
define('_LOCATIONS_LOCATION_1_LATLNG', '54.327828,10.129710');
define('_LOCATIONS_LOCATION_1_LOGO', '');
define('_LOCATIONS_LOCATION_2_LOCATIONID', '2');
define('_LOCATIONS_LOCATION_2_NAME', 'weltruf');
define('_LOCATIONS_LOCATION_2_STREET', 'Lange Reihe 21');
define('_LOCATIONS_LOCATION_2_ZIP', '24103');
define('_LOCATIONS_LOCATION_2_CITY', 'Kiel');
define('_LOCATIONS_LOCATION_2_PHONE', '');
define('_LOCATIONS_LOCATION_2_FAX', '');
define('_LOCATIONS_LOCATION_2_URL', 'http://www.weltruf-kiel.de');
define('_LOCATIONS_LOCATION_2_EMAIL', '');
define('_LOCATIONS_LOCATION_2_COUNTRY', 'Germany');
define('_LOCATIONS_LOCATION_2_STATE', 'Schleswig-Holstein');
define('_LOCATIONS_LOCATION_2_LATLNG', '54.319375,10.132035');
define('_LOCATIONS_LOCATION_2_LOGO', '');
define('_LOCATIONS_LOCATION_3_LOCATIONID', '3');
define('_LOCATIONS_LOCATION_3_NAME', 'Metro Kino');
define('_LOCATIONS_LOCATION_3_STREET', 'Holtenauerstraﬂe 162');
define('_LOCATIONS_LOCATION_3_ZIP', '24105');
define('_LOCATIONS_LOCATION_3_CITY', 'Kiel');
define('_LOCATIONS_LOCATION_3_PHONE', '');
define('_LOCATIONS_LOCATION_3_FAX', '');
define('_LOCATIONS_LOCATION_3_URL', 'http://www.metro-kino-kiel.de');
define('_LOCATIONS_LOCATION_3_EMAIL', '');
define('_LOCATIONS_LOCATION_3_COUNTRY', 'Germany');
define('_LOCATIONS_LOCATION_3_STATE', 'Schleswig-Holstein');
define('_LOCATIONS_LOCATION_3_LATLNG', '54.339814,10.133697');
define('_LOCATIONS_LOCATION_3_LOGO', '');
define('_LOCATIONS_LOCATION_4_LOCATIONID', '4');
define('_LOCATIONS_LOCATION_4_NAME', 'Lunatique');
define('_LOCATIONS_LOCATION_4_STREET', 'Ziegelteich 10');
define('_LOCATIONS_LOCATION_4_ZIP', '24103');
define('_LOCATIONS_LOCATION_4_CITY', 'Kiel');
define('_LOCATIONS_LOCATION_4_PHONE', '');
define('_LOCATIONS_LOCATION_4_FAX', '');
define('_LOCATIONS_LOCATION_4_URL', '');
define('_LOCATIONS_LOCATION_4_EMAIL', '');
define('_LOCATIONS_LOCATION_4_COUNTRY', 'Germany');
define('_LOCATIONS_LOCATION_4_STATE', 'Schleswig-Holstein');
define('_LOCATIONS_LOCATION_4_LATLNG', '54.318646,10.132500');
define('_LOCATIONS_LOCATION_4_LOGO', '');
define('_LOCATIONS_LOCATION_5_LOCATIONID', '5');
define('_LOCATIONS_LOCATION_5_NAME', 'Prinz Willy');
define('_LOCATIONS_LOCATION_5_STREET', 'Lutherstraﬂe 9');
define('_LOCATIONS_LOCATION_5_ZIP', '24114');
define('_LOCATIONS_LOCATION_5_CITY', 'Kiel');
define('_LOCATIONS_LOCATION_5_PHONE', '');
define('_LOCATIONS_LOCATION_5_FAX', '');
define('_LOCATIONS_LOCATION_5_URL', 'http://www.prinzwilly.de');
define('_LOCATIONS_LOCATION_5_EMAIL', '');
define('_LOCATIONS_LOCATION_5_COUNTRY', 'Germany');
define('_LOCATIONS_LOCATION_5_STATE', 'Schleswig-Holstein');
define('_LOCATIONS_LOCATION_5_LATLNG', '54.315341,10.117084');
define('_LOCATIONS_LOCATION_5_LOGO', '');